name: code_gen

on:
  push:
    paths:
      - "swagger.yaml"
      - "openapi-generator"

env:
  DOCKER_BUILDKIT: 1

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: submodule
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: swagger
        uses: ./.github/actions/code-gen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
